spring.application.name=Mediturno

# Base de datos (Supabase / PostgreSQL)
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres.ssnfivszjlsbxhptasdf
spring.datasource.password=iFdss8c8UVivO6Td

#JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#JWT
app.jwt.secreto=EstaEsUnaClaveMuySecretaYDebeSerDeAlMenos256BitsParaHS512!!!
app.jwt.expiracion=86400000

#Servidor
server.port=8080